<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="D:\MyOS\bootloader\csharp\apps\mex.shared.props" />
  <PropertyGroup>
    <AssemblyName>FileExplorer</AssemblyName>
    <RootNamespace>App</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.cs" />
  </ItemGroup>
</Project>
