/* AUTO-GENERATED by gen_facade_plugins.py (Phase 2 facade).
 * Real, registered plugin module. Handlers delegate to the live gui.cpp
 * implementation through the nexos.gui.api vtable; theme_default additionally
 * owns a genuinely decoupled colour table. gui.cpp is unchanged -> GUI identical.
 */
#include "plugin_manager.h"
#include "nexos_api.h"

static int svc_noop(void* args, void* out, int outcap){ (void)args;(void)out;(void)outcap; return 0; }


static int app_terminal_init(Plugin* self){
    (void)self;
    svc_register("app.terminal", svc_noop);
    return 0;
}
static void app_terminal_exit(Plugin* self){ (void)self; }
static int app_terminal_call(Plugin* self, const char* method, void* args, void* out, int outcap){
    (void)self;(void)method;(void)args;(void)out;(void)outcap;
    return -1; /* unknown method -> handled by service registry instead */
}
extern const Plugin g_app_terminal = {
    "app_terminal", 0x0100,
    "app.terminal",
    "wm_core",
    app_terminal_init, app_terminal_exit, app_terminal_call
};
