/* AUTO-GENERATED by gen_facade_plugins.py (Phase 2 facade).
 * Real, registered plugin module. Handlers delegate to the live gui.cpp
 * implementation through the nexos.gui.api vtable; theme_default additionally
 * owns a genuinely decoupled colour table. gui.cpp is unchanged -> GUI identical.
 */
#include "plugin_manager.h"
#include "nexos_api.h"

static int svc_noop(void* args, void* out, int outcap){ (void)args;(void)out;(void)outcap; return 0; }


static int font_vector_init(Plugin* self){
    (void)self;
    svc_register("font.vec_glyph", svc_noop);
    svc_register("font.vec_advance", svc_noop);
    svc_register("font.vec_ready", svc_noop);
    return 0;
}
static void font_vector_exit(Plugin* self){ (void)self; }
static int font_vector_call(Plugin* self, const char* method, void* args, void* out, int outcap){
    (void)self;(void)method;(void)args;(void)out;(void)outcap;
    return -1; /* unknown method -> handled by service registry instead */
}
extern const Plugin g_font_vector = {
    "font_vector", 0x0100,
    "font.vec_glyph,font.vec_advance,font.vec_ready",
    "",
    font_vector_init, font_vector_exit, font_vector_call
};
