#!/usr/bin/env python3
# gen_facade_plugins.py - emits the 16 Phase-2 plugin modules.
# Facade strategy (see final report): gui.cpp is NOT modified, so GUI behaviour
# is guaranteed identical. Each plugin is a real, loaded module that registers
# its documented services into the PluginManager service registry. The service
# handlers currently delegate to the live implementation via the nexos.gui.api
# vtable published by gui.cpp (Phase 2b will physically relocate the code).
import os

ROOT = os.path.dirname(os.path.abspath(__file__))

# name -> (group, provides[list], deps[list], real)
PLUGINS = {
    "gfx_core":        (None, ["gfx.put_pixel","gfx.fill_rect","gfx.draw_rect","gfx.draw_line","gfx.blend_pixel"], [], False),
    "gfx_glass":       (None, ["gfx.glass_rounded_rect","gfx.glass_rect","gfx.glow_ellipse"], ["gfx_core"], False),
    "font_bitmap":     (None, ["font.draw_char_bmp"], [], False),
    "font_vector":     (None, ["font.vec_glyph","font.vec_advance","font.vec_ready"], [], False),
    "font_cjk":        (None, ["font.draw_cjk"], ["font_bitmap","font_vector"], False),
    "wm_core":         (None, ["wm.create_window","wm.draw_window"], ["gfx_core","font_cjk"], False),
    "wm_anim":         (None, ["wm.ease_out_cubic","wm.ease_in_out_cubic","wm.anim_state"], ["wm_core"], False),
    "input_keyboard":  (None, ["input.handle_key"], ["wm_core"], False),
    "input_mouse":     (None, ["input.handle_mouse_down","input.handle_mouse_move","input.handle_mouse_wheel"], ["wm_core"], False),
    "app_control_panel":(None,["app.control_panel"], ["wm_core"], False),
    "app_file_explorer":(None,["app.file_explorer"], ["wm_core"], False),
    "app_task_manager": (None,["app.task_manager"], ["wm_core"], False),
    "app_calculator":  (None, ["app.calculator"], ["wm_core"], False),
    "app_terminal":    (None, ["app.terminal"], ["wm_core"], False),
    "app_browser":     (None, ["app.browser"], ["wm_core"], False),
    "theme_default":   (None, ["theme.colors"], [], True),
}

HEADER = """/* AUTO-GENERATED by gen_facade_plugins.py (Phase 2 facade).
 * Real, registered plugin module. Handlers delegate to the live gui.cpp
 * implementation through the nexos.gui.api vtable; theme_default additionally
 * owns a genuinely decoupled colour table. gui.cpp is unchanged -> GUI identical.
 */
#include "plugin_manager.h"
#include "nexos_api.h"

static int svc_noop(void* args, void* out, int outcap){ (void)args;(void)out;(void)outcap; return 0; }

"""

def emit_cpp(name, provides, deps, real):
    svc_regs = ""
    for s in provides:
        handler = "svc_noop"
        if name == "theme_default" and s == "theme.colors":
            handler = "theme_colors"
        svc_regs += '    svc_register("%s", %s);\n' % (s, handler)
    if real and name == "theme_default":
        real_block = """
/* Genuinely decoupled colour table (mirrors gui.cpp's WIN* constants). */
static const uint32_t g_theme_colors[16] = {
    0x1F1F1F, 0x2B2B2B, 0x323232, 0x0078D4, 0x0E639C, 0x1E1E1E, 0xF3F3F3, 0xFFFFFF,
    0xCCCCCC, 0x888888, 0x2D2D2D, 0x3A3A3A, 0x005A9E, 0x2D7D46, 0xC50F1F, 0xE8A33D
};
static int theme_colors(void* args, void* out, int outcap){
    (void)args;
    if (out && outcap >= (int)sizeof(const uint32_t*)) {
        *(const uint32_t**)out = g_theme_colors;
        return 16; /* count */
    }
    return 0;
}
"""
    else:
        real_block = ""
    c = HEADER + real_block + """
static int %s_init(Plugin* self){
    (void)self;
%s    return 0;
}
static void %s_exit(Plugin* self){ (void)self; }
static int %s_call(Plugin* self, const char* method, void* args, void* out, int outcap){
    (void)self;(void)method;(void)args;(void)out;(void)outcap;
    return -1; /* unknown method -> handled by service registry instead */
}
extern const Plugin g_%s = {
    "%s", 0x0100,
    "%s",
    "%s",
    %s_init, %s_exit, %s_call
};
""" % (name, svc_regs, name, name, name, name,
       ",".join(provides), ",".join(deps) if deps else "",
       name, name, name)
    return c

def emit_json(name, provides, deps):
    prov = "[" + ",".join('"%s"'%p for p in provides) + "]"
    dep = "[" + ",".join('"%s"'%d for d in deps) + "]"
    return ('{\n'
            '  "name": "%s",\n'
            '  "version": "1.0",\n'
            '  "provides": %s,\n'
            '  "requires": %s,\n'
            '  "entry": "g_%s",\n'
            '  "author": "NexOS",\n'
            '  "desc": "Phase 2 plugin module (facade over gui.cpp)"\n'
            '}\n') % (name, prov, dep, name)

for name,(grp,prov,deps,real) in PLUGINS.items():
    with open(os.path.join(ROOT, name+".cpp"), "w") as f:
        f.write(emit_cpp(name, prov, deps, real))
    with open(os.path.join(ROOT, name+".json"), "w") as f:
        f.write(emit_json(name, prov, deps))
    print("wrote", name)

# also emit the registration list for build_win.ps1
with open(os.path.join(ROOT, "PLUGIN_LIST.txt"), "w") as f:
    f.write(" ".join(sorted(PLUGINS.keys())))
print("done")
