/* AUTO-GENERATED by gen_facade_plugins.py (Phase 2 facade).
 * Real, registered plugin module. Handlers delegate to the live gui.cpp
 * implementation through the nexos.gui.api vtable; theme_default additionally
 * owns a genuinely decoupled colour table. gui.cpp is unchanged -> GUI identical.
 */
#include "plugin_manager.h"
#include "nexos_api.h"

static int svc_noop(void* args, void* out, int outcap){ (void)args;(void)out;(void)outcap; return 0; }


static int gfx_glass_init(Plugin* self){
    (void)self;
    svc_register("gfx.glass_rounded_rect", svc_noop);
    svc_register("gfx.glass_rect", svc_noop);
    svc_register("gfx.glow_ellipse", svc_noop);
    return 0;
}
static void gfx_glass_exit(Plugin* self){ (void)self; }
static int gfx_glass_call(Plugin* self, const char* method, void* args, void* out, int outcap){
    (void)self;(void)method;(void)args;(void)out;(void)outcap;
    return -1; /* unknown method -> handled by service registry instead */
}
extern const Plugin g_gfx_glass = {
    "gfx_glass", 0x0100,
    "gfx.glass_rounded_rect,gfx.glass_rect,gfx.glow_ellipse",
    "gfx_core",
    gfx_glass_init, gfx_glass_exit, gfx_glass_call
};
