/* AUTO-GENERATED by gen_facade_plugins.py (Phase 2 facade).
 * Real, registered plugin module. Handlers delegate to the live gui.cpp
 * implementation through the nexos.gui.api vtable; theme_default additionally
 * owns a genuinely decoupled colour table. gui.cpp is unchanged -> GUI identical.
 */
#include "plugin_manager.h"
#include "nexos_api.h"

static int svc_noop(void* args, void* out, int outcap){ (void)args;(void)out;(void)outcap; return 0; }


static int input_mouse_init(Plugin* self){
    (void)self;
    svc_register("input.handle_mouse_down", svc_noop);
    svc_register("input.handle_mouse_move", svc_noop);
    svc_register("input.handle_mouse_wheel", svc_noop);
    return 0;
}
static void input_mouse_exit(Plugin* self){ (void)self; }
static int input_mouse_call(Plugin* self, const char* method, void* args, void* out, int outcap){
    (void)self;(void)method;(void)args;(void)out;(void)outcap;
    return -1; /* unknown method -> handled by service registry instead */
}
extern const Plugin g_input_mouse = {
    "input_mouse", 0x0100,
    "input.handle_mouse_down,input.handle_mouse_move,input.handle_mouse_wheel",
    "wm_core",
    input_mouse_init, input_mouse_exit, input_mouse_call
};
