/* AUTO-GENERATED by gen_facade_plugins.py (Phase 2 facade).
 * Real, registered plugin module. Handlers delegate to the live gui.cpp
 * implementation through the nexos.gui.api vtable; theme_default additionally
 * owns a genuinely decoupled colour table. gui.cpp is unchanged -> GUI identical.
 */
#include "plugin_manager.h"
#include "nexos_api.h"

static int svc_noop(void* args, void* out, int outcap){ (void)args;(void)out;(void)outcap; return 0; }


static int wm_anim_init(Plugin* self){
    (void)self;
    svc_register("wm.ease_out_cubic", svc_noop);
    svc_register("wm.ease_in_out_cubic", svc_noop);
    svc_register("wm.anim_state", svc_noop);
    return 0;
}
static void wm_anim_exit(Plugin* self){ (void)self; }
static int wm_anim_call(Plugin* self, const char* method, void* args, void* out, int outcap){
    (void)self;(void)method;(void)args;(void)out;(void)outcap;
    return -1; /* unknown method -> handled by service registry instead */
}
extern const Plugin g_wm_anim = {
    "wm_anim", 0x0100,
    "wm.ease_out_cubic,wm.ease_in_out_cubic,wm.anim_state",
    "wm_core",
    wm_anim_init, wm_anim_exit, wm_anim_call
};
