#!/usr/bin/env python3
"""
gen_zfont.py - Generate a compact GB2312 16x16 dot-matrix CJK font for MiniOS GUI.

Output: build/zfont.bin + build/zfont_data.h (C array embedded in kernel)

Format:
  Header : 'ZFN1' (4 bytes) + uint16 count (LE)
  Entry  : uint16 gb_code (LE) + uint8 glyph[32]  (16 rows x 16 cols, MSB first)
  Sorted by gb_code for binary search.

Rendering source: Windows SimSun (C:\Windows\Fonts\simsun.ttc) via /mnt/c on WSL,
or any TTF fallback.
"""
import struct, sys, os

# ---- Character set: MiniOS UI strings + high-frequency simplified Chinese ----
CHARS = (
    "欢迎使用迷你操作系统桌面系统文件编辑查看工具帮助设置关闭最小化最大化还原"
    "用户权限管理密码登录注销切换添加删除修改保存加载打开新建文件夹复制剪切粘贴"
    "重命名删除清空终端命令运行退出重启关机时间日期时钟状态信息关于版本网络服务"
    "搜索应用控制面板任务管理器计算器浏览器记事本资源管理器我的电脑回收站属性"
    "字体颜色大小位置窗口视图缩放音量亮度电源无线蓝牙显示分辨率屏幕亮度键鼠标"
    "触摸板键盘输入法中文简体标点符号数字字母空格回车确认取消确定是是否否提示"
    "警告错误成功失败完成进度正在处理等待就绪运行停止暂停继续下一步上一步完成"
    "同意拒绝允许禁止授权限制访问只读写入执行可读可写内容数据信息错误异常堆栈"
    "内存磁盘硬盘分区文件目录路径地址地址栏首页返回前进刷新停止加载网络连接断开"
    "远程桌面开始菜单任务栏托盘通知中心快捷方式图标壁纸背景主题外观个性化"
    "你好世界早上好下午好晚上好请稍等谢谢再见设置完成加载中请等待登录中"
    "您的操作无法执行没有权限请以管理员身份运行或者使用超级用户命令"
    "系统启动引导初始化内存管理文件系统网络接口图形界面图形驱动内核版本"
    "中国北京时间日期时间秒毫秒微秒纳秒千字节兆字节吉字节太字节"
    "一二三四五六七八九十百千万亿零百十"
    "大小高低长短宽窄深浅明暗远近快慢多少"
    "输入输出收发上传下载安装卸载升级更新补丁修复崩溃恢复备份恢复出厂"
    "安全加密解密认证令牌密钥证书签名哈希校验和错误检查测试诊断调试"
    "软件硬件设备驱动程序固件兼容模式启动选项引导菜单命令行提示符"
    "帮助文档手册教程示例演示体验反馈问题建议报告日志记录历史"
    "任务计划排程优先级别高级中级低级普通标准默认自定义选项参数"
)

def gb_code(ch):
    """Return GB2312 2-byte code for a char, or None if not representable."""
    try:
        b = ch.encode('gb2312')
        if len(b) == 2:
            return (b[0] << 8) | b[1]
    except Exception:
        pass
    return None

def render_glyph(ch, font):
    """Render char into 16x16 bitmap by drawing at 22px then downscaling.
    Direct 16px in SimSun yields nearly-empty glyphs.
    """
    from PIL import Image, ImageDraw
    src = Image.new('L', (22, 22), 0)
    d = ImageDraw.Draw(src)
    d.text((0, -1), ch, font=font, fill=255)
    img = src.resize((16, 16), Image.LANCZOS)
    glyph = bytearray(32)
    for row in range(16):
        for half in range(2):
            byte = 0
            for b in range(8):
                col = half * 8 + b
                if img.getpixel((col, row)) > 128:
                    byte |= 0x80 >> b
            glyph[row * 2 + half] = byte
    return bytes(glyph)

def main():
    from PIL import ImageFont
    # Font candidates (Windows SimSun via WSL mount, then common paths)
    candidates = [
        'C:\\Windows\\Fonts\\simsun.ttc',
        'C:\\Windows\\Fonts\\msyh.ttc',
        'C:\\Windows\\Fonts\\simhei.ttf',
        '/mnt/c/Windows/Fonts/simsun.ttc',
        '/mnt/c/Windows/Fonts/msyh.ttc',
        '/usr/share/fonts/truetype/wqy/wqy-microhei.ttc',
        '/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc',
    ]
    font_path = None
    for c in candidates:
        if os.path.exists(c):
            font_path = c
            break
    if not font_path:
        print("No CJK font found. Install one or mount Windows fonts."); sys.exit(1)
    print("Font:", font_path)

    entries = {}
    for ch in CHARS:
        code = gb_code(ch)
        if code is None or ch == ' ':
            continue
        if code in entries:
            continue
        try:
            font = ImageFont.truetype(font_path, 16)
            entries[code] = render_glyph(ch, font)
        except Exception as e:
            pass
    print("Rendered %d unique CJK glyphs" % len(entries))

    items = sorted(entries.items())
    os.makedirs('build', exist_ok=True)
    with open('build/zfont.bin', 'wb') as f:
        f.write(b'ZFN1')
        f.write(struct.pack('<H', len(items)))
        for code, glyph in items:
            f.write(struct.pack('<H', code))
            f.write(glyph)

    # Unicode codepoints for each entry (same order) - for UTF-8 lookup
    unicodes = []
    for code, _ in items:
        b = bytes([code >> 8, code & 0xFF])
        u = b.decode('gb2312')
        unicodes.append(ord(u))

    # C header for embedding
    with open('build/zfont_data.h', 'w', encoding='utf-8') as f:
        f.write('#pragma once\n#include <stdint.h>\n')
        f.write('// Auto-generated by tools/gen_zfont.py - GB2312 16x16 CJK font\n')
        f.write('static const uint16_t zfont_count = %d;\n' % len(items))
        f.write('static const uint16_t zfont_unicode[] = {\n')
        for i in range(0, len(unicodes), 16):
            f.write('    ' + ','.join('0x%04X' % unicodes[j] for j in range(i, min(i+16, len(unicodes)))) + ',\n')
        f.write('};\n')
        f.write('static const uint8_t zfont_glyphs[] = {\n')
        for i, (_, g) in enumerate(items):
            f.write('    ' + ','.join('%d' % b for b in g) + ',\n')
        f.write('};\n')
    print("Wrote build/zfont.bin and build/zfont_data.h (%d bytes glyph data)" % (len(items) * 32))

if __name__ == '__main__':
    main()
