<template>
  <div class="gallery-item-page">
    <div style="position: relative;" class="page-heading">
          <h1 class="page-header">AnimatedIcon</h1>
          <p class="page-description">
            AnimatedIcon is a control that displays an animated icon. These icons are created using Adobe AfterEffects and translated into Microsoft.UI.Composition objects using Lottie-Windows. The control automatically manages the animation state based on user interactions like pointer hover.
          </p>
          <div class="page-header-actions">
            <WinButton class="header-action" @click="toggleTheme"
             >
              <span class="icon">&#xE793;</span>
            </WinButton>
            <WinToggleButton class="header-action" :IsChecked="isFavoriteState"
              @update:IsChecked="toggleFavorite"
             >
              <span class="icon">{{ isFavoriteState ? '&#xE735;' : '&#xE734;' }}</span>
            </WinToggleButton>
          </div>
        </div>
    <WinScrollViewer class="gallery-page-scroll" VerticalScrollBarVisibility="Auto" VerticalScrollMode="Auto">
      <div class="gallery-page-content">
            <!-- Example 1: Adding AnimatedIcon to a button -->
            <WinControlExample
              headerText="Adding AnimatedIcon to a button"
              :theme="pageTheme"
              :templateCode="example1Template"
              :vueCode="example1Vue">
              <template #example>
                <div style="display: flex; flex-direction: column; gap: 16px; align-items: flex-start;">
                  <p style="margin: 0; font-size: 14px; color: var(--text-secondary); max-width: 500px;">
                    The following example is a button that the user hovers over to trigger the animation. The AnimatedIcon consumes the animation created using Adobe AfterEffects and translated into Microsoft.UI.Composition objects using
                    <a href="https://aka.ms/lottie" style="color: var(--accent-base);">Lottie-Windows</a>.
                  </p>
                  <WinButton @mouseenter="onButtonPointerEntered"
                    @mouseleave="onButtonPointerExited"
                    style="width: 75px; height: 40px;">
                    <WinAnimatedVisualPlayer
                      :playing="isAnimationPlaying"
                      :reversed="isAnimationReversed"
                      :duration="800" />
                  </WinButton>
                </div>
              </template>
              <template #options>
                <div style="display: flex; flex-direction: column; gap: 8px;">
                  <label style="font-size: 12px; color: var(--text-secondary);">Kind</label>
                  <WinComboBox
                    v-model:SelectedIndex="selectedAnimationKindIndex"
                    :ItemsSource="animationKindOptions"
                    DisplayMemberPath="label"
                    style="min-width: 240px;" />
                </div>
              </template>
            </WinControlExample>

            <!-- Example 2: Adding AnimatedIcon to NavigationView -->
            <WinControlExample
              headerText="Adding AnimatedIcon to a NavigationView"
              :theme="pageTheme"
              :templateCode="example2Template"
              :vueCode="example2Vue">
              <template #example>
                <div style="display: flex; flex-direction: column; gap: 16px;">
                  <p style="margin: 0; font-size: 14px; color: var(--text-secondary); max-width: 500px;">
                    If you set an AnimatedIcon as the value of the Icon property, the NavigationViewItem will set the states of the AnimatedIcon for you, according to the states of the control. For this example, this shows a custom animation that was generated by the LottieGen tool.
                  </p>
                  <div style="padding: 12px; border: 1px solid var(--ctrl-border-rest); border-radius: 8px; background: var(--card-bg-secondary);">
                    <div style="display: flex; align-items: center; gap: 12px; padding: 8px; cursor: pointer; border-radius: 4px; transition: background 0.1s;"
                         @mouseenter="onNavItemEnter"
                         @mouseleave="onNavItemLeave"
                         :style="{ background: isNavItemHovered ? 'var(--ctrl-fill-subtle)' : 'transparent' }">
                      <div style="width: 32px; height: 32px; display: flex; align-items: center; justify-content: center;">
                        <WinAnimatedVisualPlayer
                          :playing="isNavAnimationPlaying"
                          :reversed="false"
                          :duration="600" />
                      </div>
                      <span style="font-size: 14px; color: var(--text-primary);">Game Settings</span>
                    </div>
                  </div>
                </div>
              </template>
            </WinControlExample>
      </div>
    </WinScrollViewer>
  </div>
</template>

<script setup>
import { ref, computed, inject } from 'vue';
import WinButton from '../../components/WinButton.vue';
import WinToggleButton from '../../components/WinToggleButton.vue';
import WinComboBox from '../../components/WinComboBox.vue';
import WinAnimatedVisualPlayer from '../../components/WinAnimatedVisualPlayer.vue';
import WinControlExample from '../../components/WinControlExample.vue';
import { createPageState } from '../../utils/pageState';

import WinScrollViewer from '../../components/WinScrollViewer.vue';
const currentPage = inject('currentPage');
const pageKey = computed(() => currentPage?.value || 'animatedicon');

const { isFavoriteState, pageTheme, toggleTheme, toggleFavorite } = createPageState(pageKey.value);

// Example 1: Button with AnimatedIcon
const isAnimationPlaying = ref(false);
const isAnimationReversed = ref(false);
const selectedAnimationKindIndex = ref(4); // Default to AnimatedFindVisualSource

const animationKindOptions = [
  { label: 'AnimatedBackVisualSource' },
  { label: 'AnimatedChevronDownSmallVisualSource' },
  { label: 'AnimatedChevronRightDownSmallVisualSource' },
  { label: 'AnimatedChevronUpDownSmallVisualSource' },
  { label: 'AnimatedFindVisualSource' },
  { label: 'AnimatedGlobalNavigationButtonVisualSource' },
  { label: 'AnimatedSettingsVisualSource' }
];

const onButtonPointerEntered = () => {
  isAnimationPlaying.value = true;
  isAnimationReversed.value = false;
};

const onButtonPointerExited = () => {
  isAnimationPlaying.value = false;
};

// Example 2: NavigationView with AnimatedIcon
const isNavItemHovered = ref(false);
const isNavAnimationPlaying = ref(false);

const onNavItemEnter = () => {
  isNavItemHovered.value = true;
  isNavAnimationPlaying.value = true;
};

const onNavItemLeave = () => {
  isNavItemHovered.value = false;
  isNavAnimationPlaying.value = false;
};

// Code examples
const example1Template = `<WinButton @mouseenter="onButtonPointerEntered"
  @mouseleave="onButtonPointerExited"
  style="width: 75px;">
  <AnimatedIcon x:Name="SearchAnimatedIcon">
    <AnimatedIcon.Source>
      <animatedvisuals:AnimatedFindVisualSource/>
    </AnimatedIcon.Source>
    <AnimatedIcon.FallbackIconSource>
      <SymbolIconSource Symbol="Find"/>
    </AnimatedIcon.FallbackIconSource>
  </AnimatedIcon>
</WinButton>`;

const example1Vue = `const isAnimationPlaying = ref(false);

const onButtonPointerEntered = () => {
  // Set AnimatedIcon state to "PointerOver"
  isAnimationPlaying.value = true;
};

const onButtonPointerExited = () => {
  // Set AnimatedIcon state to "Normal"
  isAnimationPlaying.value = false;
};`;

const example2Template = `<NavigationView>
  <NavigationView.MenuItems>
    <NavigationViewItem Content="Game Settings">
      <NavigationViewItem.Icon>
        <AnimatedIcon x:Name='AnimatedIcon'>
          <AnimatedIcon.Source>
            <animatedvisuals:AnimatedSettingsVisualSource/>
          </AnimatedIcon.Source>
          <AnimatedIcon.FallbackIconSource>
            <FontIconSource Glyph="&#xE713;"/>
          </AnimatedIcon.FallbackIconSource>
        </AnimatedIcon>
      </NavigationViewItem.Icon>
    </NavigationViewItem>
  </NavigationView.MenuItems>
</NavigationView>`;

const example2Vue = `// NavigationViewItem automatically manages AnimatedIcon states
// based on user interactions (hover, selection, etc.)

const isNavAnimationPlaying = ref(false);

const onNavItemEnter = () => {
  isNavAnimationPlaying.value = true;
};

const onNavItemLeave = () => {
  isNavAnimationPlaying.value = false;
};`;
</script>

<style scoped>
.page-header {
  font-size: 28px;
  font-weight: 600;
  margin: 0 0 8px 0;
  color: var(--text-primary);
}

.page-description {
  font-size: 14px;
  color: var(--text-secondary);
  margin: 0 0 16px 0;
  line-height: 1.5;
}

.page-header-actions {
  position: absolute;
  top: 0;
  right: 0;
  display: flex;
  gap: 4px;
  align-items: center;
}

.icon {
  font-size: 16px;
}
</style>
