#!/usr/bin/env python3
r"""
gen_latin_font_a.py - Generate a grayscale (anti-aliased) Latin font for NexOS.

Output: gui_font_a.h
  - const uint8_t g_fontA_w[128];      // per-glyph pixel width (4..12)
  - const uint8_t g_fontA[128*12*24];  // 12x24 alpha (0..255), row-major, 12 cols

The kernel renders this with alpha blending (blend_rect / per-pixel mix) so
text edges are smooth instead of hard 1-bit pixels.

Glyphs 0x20..0x7E are baked from Microsoft YaHei (msyh.ttc). Other slots are
left zero (control chars / legacy CP437 are not re-baked here; the kernel
keeps its legacy 1-bit font8x16 for those if needed).

Usage:
  python tools/gen_latin_font_a.py
"""
import struct, os, sys
from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT  = os.path.join(ROOT, 'gui_font_a.h')

GW, GH = 12, 24            # glyph cell (display size)
TARGET_H = 20             # ink height, leaves a little breathing room

CANDIDATES = [
    r'C:\Windows\Fonts\msyh.ttc',
    r'C:\Windows\Fonts\msyhbd.ttc',
    '/mnt/c/Windows/Fonts/msyh.ttc',
    '/usr/share/fonts/truetype/wqy/wqy-microhei.ttc',
]

def find_font():
    for c in CANDIDATES:
        if os.path.exists(c):
            return c
    return None

def render_glyph(ch, font):
    """Return (width, alpha_bytes[GH][GW]) for a char, or (0, None)."""
    src = Image.new('L', (64, 64), 0)
    d = ImageDraw.Draw(src)
    try:
        d.text((6, 4), ch, font=font, fill=255)
    except Exception:
        return 0, None
    bbox = src.getbbox()
    if bbox is None:
        return 0, None
    ink = src.crop(bbox)
    iw, ih = ink.size
    if ih == 0 or iw == 0:
        return 0, None
    # scale to TARGET_H, keep aspect, cap width at GW
    th = TARGET_H
    tw = max(1, int(round(iw * th / ih)))
    if tw > GW:
        tw = GW
        th = max(1, int(round(ih * tw / iw)))
    scl = ink.resize((tw, th), Image.LANCZOS)
    out = Image.new('L', (GW, GH), 0)
    ox = (GW - tw) // 2
    oy = GH - th                 # baseline at bottom
    out.paste(scl, (ox, oy))
    rows = []
    for r in range(GH):
        rows.append([out.getpixel((c, r)) for c in range(GW)])
    return tw, rows

def main():
    fp = find_font()
    if not fp:
        print("No Microsoft YaHei font found."); sys.exit(1)
    print("Latin font:", fp)
    try:
        font = ImageFont.truetype(fp, 40, index=0)
    except TypeError:
        font = ImageFont.truetype(fp, 40)

    widths = [0]*128
    data = bytearray(128 * GW * GH)
    for cp in range(0x20, 0x7F):
        w, rows = render_glyph(chr(cp), font)
        widths[cp] = w
        if rows is None:
            continue
        base = cp * GW * GH
        for r in range(GH):
            for c in range(GW):
                data[base + r*GW + c] = rows[r][c]

    with open(OUT, 'w', encoding='utf-8') as f:
        f.write("// Auto-generated by tools/gen_latin_font_a.py - grayscale 12x24 Latin font\n")
        f.write("// Microsoft YaHei, anti-aliased. Per-glyph width + 0..255 alpha.\n")
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write("#define FONT_A_W %d\n#define FONT_A_H %d\n\n" % (GW, GH))
        f.write("static const uint8_t g_fontA_w[128] = {\n")
        for i in range(0, 128, 16):
            f.write("    " + ",".join("%2d" % widths[j] for j in range(i, i+16)) + ",\n")
        f.write("};\n\n")
        f.write("static const uint8_t g_fontA[%d] = {\n" % (128*GW*GH))
        for cp in range(128):
            f.write("    // 0x%02X\n" % cp)
            blk = data[cp*GW*GH:(cp+1)*GW*GH]
            for r in range(GH):
                row = blk[r*GW:(r+1)*GW]
                f.write("    " + ",".join("%3d" % v for v in row) + ",\n")
        f.write("};\n")
    print("Wrote", OUT, "(%d bytes alpha data)" % len(data))

if __name__ == '__main__':
    main()
