#!/usr/bin/env python3
"""Convert assets/Logo.png into logo.h: a 256x128 RGB565 + alpha boot splash.

The source image has a deep-blue background.  Pixels close to that background
are emitted with alpha=0 so the kernel can composite the cyan/white logo
glyph cleanly onto the same deep-blue backdrop without a visible rectangle."""
from PIL import Image
import os

SRC = os.path.join(os.path.dirname(__file__), "..", "assets", "Logo.png")
OUT = os.path.join(os.path.dirname(__file__), "..", "logo.h")
W, H = 256, 128


def rgb565(r, g, b):
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


im = Image.open(SRC).convert("RGB")
im = im.resize((W, H), Image.LANCZOS)
px = im.load()

# Background colour = average of four corner pixels (the deep-blue backdrop).
corners = [(0, 0), (W - 1, 0), (0, H - 1), (W - 1, H - 1)]
bg = [sum(px[x, y][c] for x, y in corners) // 4 for c in range(3)]
bg_r, bg_g, bg_b = bg

rgb_rows = []
a_rows = []

for y in range(H):
    rgb_parts = []
    a_parts = []
    for x in range(W):
        r, g, b = px[x, y]
        # Distance from background.  Use a max channel distance for a
        # forgiving "key", then smoothstep to an alpha value.
        d = max(abs(r - bg_r), abs(g - bg_g), abs(b - bg_b))
        if d <= 6:
            alpha = 0
        elif d >= 42:
            alpha = 255
        else:
            alpha = int((d - 6) * 255 / 36)
        rgb_parts.append("0x%04X" % rgb565(r, g, b))
        a_parts.append("0x%02X" % alpha)
    rgb_rows.append("    " + ",".join(rgb_parts))
    a_rows.append("    " + ",".join(a_parts))

with open(OUT, "w", encoding="utf-8") as f:
    f.write("// Auto-generated by tools/gen_logo.py from assets/Logo.png\n")
    f.write("// 256x128 RGB565+A boot splash (do not edit by hand).\n")
    f.write("#ifndef NEXOS_LOGO_H\n#define NEXOS_LOGO_H\n\n")
    f.write("#define LOGO_W %d\n#define LOGO_H %d\n\n" % (W, H))
    f.write("static const uint16_t g_logo_rgb[LOGO_W * LOGO_H] = {\n")
    f.write(",\n".join(rgb_rows))
    f.write("\n};\n\n")
    f.write("static const uint8_t g_logo_a[LOGO_W * LOGO_H] = {\n")
    f.write(",\n".join(a_rows))
    f.write("\n};\n\n#endif // NEXOS_LOGO_H\n")

print("wrote", OUT, "(%dx%d, rgb=%d bytes, a=%d bytes)" % (W, H, W * H * 2, W * H))
