/*
 * gen_bitmap_fonts.c - Host-side rasterizer that bakes the NexOS bitmap fonts
 * from a TrueType source (msyh.ttf) using stb_truetype's grayscale coverage.
 *
 * Produces TWO fonts, both 8-bit alpha (per-pixel coverage 0..255):
 *
 *  1) ASCII 16x16  -> build/afont_data.h   (embedded in the kernel; 95 glyphs)
 *  2) CJK   24x24  -> sfs_files/zfont.bin  (full GB2312; loaded from SFS)
 *
 * The 8-bit alpha channel is what draw_char()/draw_cjk() blend with, so text
 * edges are anti-aliased instead of the old 1-bit binary stamp.
 *
 * Build/run (WSL):
 *   gcc -O2 -o build/gen_bitmap_fonts tools/gen_bitmap_fonts.c -I tools/stb
 *   ./build/gen_bitmap_fonts sfs_files/msyh.ttf \
 *       build/afont_data.h sfs_files/zfont.bin build/gb2312_uni.txt
 *
 * ZFN3 file format (little-endian):
 *   char   magic[4] = "ZFN3"
 *   uint16 count
 *   uint16 px                 (glyph cell = px*px)
 *   uint16 unicode[count]     (ascending, binary-searchable)
 *   uint8  glyph[count][px*px](row-major, 1 byte alpha/pixel)
 */
#define STB_TRUETYPE_IMPLEMENTATION
#include "stb_truetype.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static unsigned char* slurp(const char* path, long* out_sz) {
    FILE* f = fopen(path, "rb");
    if (!f) { fprintf(stderr, "open %s failed\n", path); return NULL; }
    fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
    unsigned char* b = (unsigned char*)malloc(sz);
    if (!b || fread(b, 1, sz, f) != (size_t)sz) { fclose(f); free(b); return NULL; }
    fclose(f);
    if (out_sz) *out_sz = sz;
    return b;
}

/* Blit an stb coverage bitmap into a px*px cell with a small left/top origin.
 * We anchor glyphs by their baseline so Latin sits on the text baseline and
 * CJK fills the em box. */
static void place_glyph(const unsigned char* bmp, int bw, int bh,
                        unsigned char* cell, int px,
                        int ox, int oy) {
    for (int y = 0; y < bh; y++) {
        int dy = y + oy;
        if (dy < 0 || dy >= px) continue;
        const unsigned char* srow = bmp + (size_t)y * bw;
        unsigned char* drow = cell + (size_t)dy * px;
        for (int x = 0; x < bw; x++) {
            int dx = x + ox;
            if (dx < 0 || dx >= px) continue;
            unsigned char v = srow[x];
            if (v > drow[dx]) drow[dx] = v;    /* max-combine on overlap */
        }
    }
}

int main(int argc, char** argv) {
    const char* ttf     = argc > 1 ? argv[1] : "sfs_files/msyh.ttf";
    const char* afont_h = argc > 2 ? argv[2] : "build/afont_data.h";
    const char* zfont_b = argc > 3 ? argv[3] : "sfs_files/zfont.bin";
    const char* uilist  = argc > 4 ? argv[4] : "build/gb2312_uni.txt";

    const int AW = 16, AH = 16;     /* ASCII cell */
    const int CW = 24, CH = 24;     /* CJK cell   */
    const int A_BASE = 0x20, A_COUNT = 95;   /* 0x20..0x7E */

    long tsz = 0;
    unsigned char* ttf_buf = slurp(ttf, &tsz);
    if (!ttf_buf) return 1;
    stbtt_fontinfo font;
    if (!stbtt_InitFont(&font, ttf_buf, stbtt_GetFontOffsetForIndex(ttf_buf, 0))) {
        fprintf(stderr, "stbtt_InitFont failed for %s\n", ttf); return 1;
    }

    /* ---------------- ASCII 16x16 ---------------- */
    float asc_scale = stbtt_ScaleForPixelHeight(&font, (float)AW);
    int a_asc, a_desc, a_gap;
    stbtt_GetFontVMetrics(&font, &a_asc, &a_desc, &a_gap);
    int a_base = (int)(a_asc * asc_scale + 0.5f);   /* baseline y within cell */

    unsigned char (*a_cell)[AW * AH] = malloc((size_t)A_COUNT * AW * AH);
    unsigned char a_adv[A_COUNT];
    memset(a_cell, 0, (size_t)A_COUNT * AW * AH);
    for (int i = 0; i < A_COUNT; i++) {
        int cp = A_BASE + i, w = 0, h = 0, xo = 0, yo = 0;
        unsigned char* bmp = stbtt_GetCodepointBitmap(&font, asc_scale, asc_scale,
                                                      cp, &w, &h, &xo, &yo);
        int oy = a_base + yo;           /* stb yo is relative to baseline */
        if (bmp) {
            place_glyph(bmp, w, h, a_cell[i], AW, xo, oy);
            stbtt_FreeBitmap(bmp, 0);
        }
        int adv = 0, lsb = 0;
        stbtt_GetCodepointHMetrics(&font, cp, &adv, &lsb);
        int apx = (int)(adv * asc_scale + 0.5f);
        if (apx < 1) apx = 1;
        if (apx > AW) apx = AW;
        a_adv[i] = (unsigned char)apx;
    }

    FILE* fh = fopen(afont_h, "w");
    if (!fh) { fprintf(stderr, "open %s failed\n", afont_h); return 1; }
    fprintf(fh, "#pragma once\n#include <stdint.h>\n");
    fprintf(fh, "// Auto-generated by tools/gen_bitmap_fonts.c -- 16x16 8-bit-alpha ASCII\n");
    fprintf(fh, "#define AFONT_FIRST %d\n#define AFONT_COUNT %d\n#define AFONT_W %d\n#define AFONT_H %d\n",
            A_BASE, A_COUNT, AW, AH);
    fprintf(fh, "static const uint8_t afont_adv[AFONT_COUNT] = {\n");
    for (int i = 0; i < A_COUNT; i++) {
        fprintf(fh, "%d,", a_adv[i]);
        if ((i & 31) == 31) fputc('\n', fh);
    }
    fprintf(fh, "\n};\n");
    fprintf(fh, "static const uint8_t afont_alpha[AFONT_COUNT][AFONT_W*AFONT_H] = {\n");
    for (int i = 0; i < A_COUNT; i++) {
        fprintf(fh, "{");
        for (int p = 0; p < AW * AH; p++) {
            fprintf(fh, "%d,", a_cell[i][p]);
            if ((p & 31) == 31) fputc('\n', fh);
        }
        fprintf(fh, "},\n");
    }
    fprintf(fh, "};\n");
    fclose(fh);
    printf("ASCII: %d glyphs %dx%d -> %s\n", A_COUNT, AW, AH, afont_h);

    /* ---------------- CJK 24x24 (GB2312 list) ---------------- */
    FILE* lf = fopen(uilist, "r");
    if (!lf) { fprintf(stderr, "open list %s failed (run gen_gb2312_list.py first)\n", uilist); return 1; }
    int cap = 8192, n = 0;
    unsigned short* cps = malloc(sizeof(unsigned short) * cap);
    while (n < cap && fscanf(lf, "%hu", &cps[n]) == 1) n++;
    fclose(lf);

    float cjk_scale = stbtt_ScaleForPixelHeight(&font, (float)CH);
    int c_asc, c_desc, c_gap;
    stbtt_GetFontVMetrics(&font, &c_asc, &c_desc, &c_gap);
    int c_base = (int)(c_asc * cjk_scale + 0.5f);
    if (c_base < 0) c_base = 0;
    if (c_base > CH) c_base = CH;

    /* First pass: rasterize every codepoint, keeping only real glyphs.  The
       unicode index and the glyph payload MUST stay strictly parallel, so we
       collect both together and never write an index for a skipped glyph. */
    unsigned char*  cell     = malloc((size_t)CW * CH);
    unsigned short* keep_cp  = malloc(sizeof(unsigned short) * (size_t)n);
    unsigned char*  keep_buf = malloc((size_t)n * CW * CH);
    if (!cell || !keep_cp || !keep_buf) { fprintf(stderr, "oom\n"); return 1; }
    int kept = 0, blank = 0;
    for (int i = 0; i < n; i++) {
        memset(cell, 0, (size_t)CW * CH);
        int cp = cps[i], w = 0, h = 0, xo = 0, yo = 0;
        unsigned char* bmp = stbtt_GetCodepointBitmap(&font, cjk_scale, cjk_scale,
                                                      cp, &w, &h, &xo, &yo);
        int nonzero = 0;
        if (bmp) {
            /* centre horizontally a touch, drop to baseline */
            int ox = (CW - w) / 2;
            if (ox < 0) ox = 0;
            place_glyph(bmp, w, h, cell, CW, ox, c_base + yo);
            for (int p = 0; p < CW * CH; p++) if (cell[p]) nonzero++;
            stbtt_FreeBitmap(bmp, 0);
        }
        if (nonzero < 3) { blank++; continue; }   /* tofu / missing -> skip */
        keep_cp[kept] = (unsigned short)cp;
        memcpy(keep_buf + (size_t)kept * CW * CH, cell, (size_t)CW * CH);
        kept++;
    }

    FILE* zf = fopen(zfont_b, "wb");
    if (!zf) { fprintf(stderr, "open %s failed\n", zfont_b); return 1; }
    fwrite("ZFN3", 1, 4, zf);
    unsigned short k16 = (unsigned short)kept;
    fwrite(&k16, 2, 1, zf);
    unsigned short px16 = (unsigned short)CW;
    fwrite(&px16, 2, 1, zf);
    fwrite(keep_cp, 2, (size_t)kept, zf);          /* ascending, parallel */
    fwrite(keep_buf, 1, (size_t)kept * CW * CH, zf);
    long total = ftell(zf);
    fclose(zf);

    printf("CJK: %d/%d glyphs %dx%d kept (%d blank) -> %s (%.2f MB)\n",
           kept, n, CW, CH, blank, zfont_b, total / 1048576.0);

    free(keep_buf); free(keep_cp); free(cell); free(cps); free(a_cell); free(ttf_buf);
    return 0;
}
