#!/usr/bin/env python3
"""
gen_ime_dict.py - Generate a pinyin -> Hanzi dictionary for the NexOS IME.

Reads the glyph unicode set from build/zfont_data.h, computes pinyin for each
char via pypinyin, and emits build/ime_dict.h sorted by pinyin for prefix matching.

Format:
  static const char   ime_pinyin[][8];   // e.g. "huan"
  static const uint16_t ime_unicode[];    // e.g. 0x6B22 (欢)
  static const int     ime_count;
"""
import re, struct, os, sys
from pypinyin import lazy_pinyin

def main():
    # 1) Extract unicode codepoints from zfont_data.h
    hdr = open('build/zfont_data.h', encoding='utf-8').read()
    m = re.search(r'static const uint16_t zfont_unicode\[\] = \{(.*?)\};', hdr, re.S)
    if not m:
        print("zfont_unicode not found in build/zfont_data.h"); sys.exit(1)
    unis = [int(x.strip(), 16) for x in m.group(1).split(',') if x.strip()]
    print("Glyphs:", len(unis))

    # 2) Compute pinyin for each
    entries = []   # (pinyin, unicode)
    for u in unis:
        ch = chr(u)
        py = lazy_pinyin(ch)[0] if ch else ''
        # keep only a-z pinyin
        py = ''.join(c for c in py if 'a' <= c <= 'z')
        if py:
            entries.append((py, u))
    entries.sort(key=lambda e: e[0])   # sort by pinyin for binary search
    print("Entries with pinyin:", len(entries))

    # 3) Emit ime_dict.h
    with open('build/ime_dict.h', 'w', encoding='utf-8') as f:
        f.write('#pragma once\n#include <stdint.h>\n')
        f.write('// Auto-generated by tools/gen_ime_dict.py - pinyin->Hanzi IME dictionary\n')
        f.write('static const int ime_count = %d;\n' % len(entries))
        f.write('static const char ime_pinyin[][8] = {\n')
        for i in range(0, len(entries), 12):
            f.write('    ' + ','.join('"%s"' % entries[j][0] for j in range(i, min(i+12, len(entries)))) + ',\n')
        f.write('};\n')
        f.write('static const uint16_t ime_unicode[] = {\n')
        for i in range(0, len(entries), 12):
            f.write('    ' + ','.join('0x%04X' % entries[j][1] for j in range(i, min(i+12, len(entries)))) + ',\n')
        f.write('};\n')
    print("Wrote build/ime_dict.h (%d entries)" % len(entries))

if __name__ == '__main__':
    main()
