#!/usr/bin/env python3
# Generate font16x16.h (const uint8_t font16x16[256][32]) for NexOS.
#
# ASCII (0x20-0x7F) source, in priority order:
#   1. tools/unifont.hex  (real Unifont .hex dump, BMP plane 0 must contain
#      0x20-0x7F).  Standard Unifont 16x16 = 16 rows x 16 bits = 32 hex digits.
#   2. gui.cpp's font8x16[256][16] table, SCALED to 16x16 by replicating each
#      column x2 (so the complete, correct 8x16 ASCII glyphs become 16px wide).
#      This is used when no full Unifont .hex is available (e.g. offline).
#
# Output: font16x16[256][32], ASCII populated, 0x80-0xFF zero-filled,
# 16x16 bitmap, 2 bytes/row, most-significant byte first.

import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GUI = os.path.join(REPO, "gui.cpp")
OUT = os.path.join(REPO, "font16x16.h")
W, H = 16, 16


def parse_unifont_hex(path):
    out = {}
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        for line in f:
            line = line.strip()
            if not line or ":" not in line:
                continue
            cp_hex, bits = line.split(":", 1)
            try:
                cp = int(cp_hex, 16)
            except ValueError:
                continue
            bits = bits.replace(" ", "")
            n = len(bits) // 4
            if n < 1:
                continue
            rows = [int(bits[r * 4:r * 4 + 4], 16) for r in range(min(n, H))]
            out[cp] = rows
    return out


def parse_font8x16_from_gui():
    """Extract the font8x16[256][16] 1-byte-per-row table from gui.cpp."""
    src = open(GUI, "r", encoding="utf-8", errors="replace").read()
    m = re.search(r"font8x16\[256\]\[16\]\s*=\s*\{(.*?)\};", src, re.S)
    if not m:
        raise RuntimeError("font8x16 table not found in gui.cpp")
    body = m.group(1)
    nums = [int(x, 16) for x in re.findall(r"0x([0-9A-Fa-f]{2})", body)]
    assert len(nums) == 256 * 16, "unexpected font8x16 length %d" % len(nums)
    table = [nums[i * 16:(i + 1) * 16] for i in range(256)]
    return table


def scale8to16(table):
    """Scale 8x16 -> 16x16 by duplicating each column (width x2)."""
    out = [[0] * 32 for _ in range(256)]
    for cp in range(256):
        for row in range(H):
            orig = table[cp][row]  # 8 bits
            new16 = 0
            for col in range(8):
                if orig & (1 << (7 - col)):
                    new16 |= (3 << (14 - 2 * col))  # fill 2 adjacent bits
            out[cp][row * 2 + 0] = (new16 >> 8) & 0xFF
            out[cp][row * 2 + 1] = new16 & 0xFF
    return out


def hex_rows_to_bytes(rows):
    g = [0] * 32
    for r in range(min(len(rows), H)):
        v = rows[r] & 0xFFFF
        g[r * 2 + 0] = (v >> 8) & 0xFF
        g[r * 2 + 1] = v & 0xFF
    return g


def main():
    hex_path = None
    for cand in (os.path.join(REPO, "tools", "unifont.hex"),):
        if os.path.exists(cand):
            hex_path = cand
    if "--hex" in sys.argv:
        i = sys.argv.index("--hex")
        if i + 1 < len(sys.argv):
            hex_path = sys.argv[i + 1]

    glyphs = [[0] * 32 for _ in range(256)]

    # 1) Real Unifont .hex (preferred)
    if hex_path and os.path.exists(hex_path):
        print("using unifont hex:", hex_path)
        hm = parse_unifont_hex(hex_path)
        for cp, rows in hm.items():
            if 0 <= cp < 256:
                glyphs[cp] = hex_rows_to_bytes(rows)

    # 2) Fallback: scale the in-tree font8x16 8x16 ASCII table to 16x16
    if not any(any(glyphs[cp]) for cp in range(0x20, 0x80)):
        print("scaling font8x16 (8x16) -> 16x16 for ASCII")
        table = parse_font8x16_from_gui()
        scaled = scale8to16(table)
        for cp in range(256):
            glyphs[cp] = scaled[cp]

    with open(OUT, "w") as f:
        f.write("/* Auto-generated by tools/gen_font16x16.py\n")
        f.write(" * 16x16 ASCII bitmap font (2 bytes/row, MSB first).\n")
        f.write(" * Source: Unifont .hex when present, else gui.cpp font8x16\n")
        f.write(" * scaled 8x16 -> 16x16. 0x80-0xFF zero-filled.\n")
        f.write(" */\n")
        f.write("#ifndef FONT16X16_H\n")
        f.write("#define FONT16X16_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write("const uint8_t font16x16[256][32] = {\n")
        for cp in range(256):
            row = ",".join("0x%02X" % b for b in glyphs[cp])
            if cp % 8 == 0:
                f.write("  /* 0x%02X */ {" % cp)
            else:
                f.write(" {")
            f.write(row)
            f.write("}" + ("," if cp != 255 else ""))
            f.write("\n" if (cp % 8 == 7 or cp == 255) else "")
        f.write("};\n\n")
        f.write("#endif /* FONT16X16_H */\n")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
