#!/usr/bin/env python3
"""Generate a minimal but format-valid GGUF fixture for the NexOS ggml
adapter self-test (tools/gguf_loader.c).  This lets Phase 0 verification run
on QEMU without embedding a multi-GB real model: the loader parses real GGUF
structures (magic/version/KV metadata/tensor table) straight out of a tiny
byte array resident in RAM.

Output: gguf_fixture.h in the repo root (a static const byte array).

The byte layout is the exact inverse of gguf_loader.c's reader:
  magic "GGUF" | version u32 | tensor_count u64 | kv_count u64
  then KV entries:  key(string) | type u32 | value
  then tensor entries: name(string) | n_dims u32 | dims u64[] | type u32 | offset u64
"""
import struct
import sys
import os

def u32(v): return struct.pack('<I', v & 0xFFFFFFFF)
def u64(v): return struct.pack('<Q', v & 0xFFFFFFFFFFFFFFFF)

def gstr(s):
    b = s.encode('utf-8') if isinstance(s, str) else s
    return u64(len(b)) + b

def gkv(key, vtype, val):
    return gstr(key) + u32(vtype) + val

out = bytearray()
out += b'GGUF'
out += u32(3)          # version

# ---- metadata KV ----
kv = bytearray()
kv += gkv('general.architecture', 8, gstr('testarch'))
kv += gkv('general.quantization_type', 8, gstr('Q4_0'))
kv += gkv('testarch.block_count', 4, u32(12))
kv += gkv('testarch.embedding_length', 4, u32(32))
kv += gkv('testarch.attention.head_count', 4, u32(8))
# tokenizer.ggml.tokens: ARRAY of STRING
toks = [b'<unk>', b'<s>', b'</s>', b'hello', b'world']
arr = u32(8) + u64(len(toks))
for t in toks:
    arr += gstr(t)
kv += gkv('tokenizer.ggml.tokens', 9, arr)
# tokenizer.ggml.merges: ARRAY of STRING (empty is fine)
kv += gkv('tokenizer.ggml.merges', 9, u32(8) + u64(0))

kv_count = 7
tensor_count = 2

out += u64(tensor_count)
out += u64(kv_count)
out += kv

# ---- tensor info ----
def tens(name, dims, ttype, offset):
    b = gstr(name)
    b += u32(len(dims))
    for d in dims:
        b += u64(d)
    b += u32(ttype)
    b += u64(offset)
    return b

out += tens('tok_embeddings.weight', [12, 32], 2, 0)      # Q4_0
out += tens('output_norm.weight', [32], 1, 256)           # F16

# ---- pad header to alignment (32) then add dummy tensor data ----
hdr_len = len(out)
tdata = (hdr_len + 31) & ~31
out += b'\x00' * (tdata - hdr_len)
out += b'\x00' * 512

# ---- emit C header ----
here = os.path.dirname(os.path.abspath(__file__))
dst = os.path.join(here, '..', 'gguf_fixture.h') if os.path.basename(here) == 'tools' else os.path.join(here, 'gguf_fixture.h')
dst = os.path.normpath(dst)
hexbytes = ',\n'.join(
    ','.join('0x%02X' % out[i] for i in range(start, min(start + 16, len(out))))
    for start in range(0, len(out), 16)
)
with open(dst, 'w') as f:
    f.write('// Auto-generated by tools/make_test_gguf.py -- minimal valid GGUF fixture.\n')
    f.write('// Parsed by gguf_loader.c in the Phase 0 adapter self-test.\n')
    f.write('#ifndef GGUF_FIXTURE_H\n#define GGUF_FIXTURE_H\n\n')
    f.write('static const unsigned char k_gguf_fixture[] = {\n')
    f.write(hexbytes)
    f.write('\n};\n')
    f.write('static const uint64_t k_gguf_fixture_size = %d;\n\n' % len(out))
    f.write('#endif // GGUF_FIXTURE_H\n')

print('fixture bytes: %d -> %s' % (len(out), dst))
